COP-5459: Create schema for groups table
UKHomeOffice/RefData pull request #298
Opened 2021-05-10 06:59 UTC by rfndn

Create schema for the new groups functionality outlined in COP-5459

2021-05-10 07:12 UTC, pixie79 requested changes
This should not exist

2021-05-10 07:17 UTC, pixie79 commented on flyway/schemas/reference/V137__groups.sql
> +COMMENT ON COLUMN groups.code IS '{"label": "Code", "description": "The code of the group. This corresponds to the team code if Group Type is Team.", "summaryview": "true"}';
Code makes no sense if you have name as the businessKey

2021-05-10 07:18 UTC, pixie79 commented on flyway/schemas/reference/V137__groups.sql
> +COMMENT ON COLUMN groups.branchid IS '{"label": "Branch", "description": "Branch of the group.", "summaryview": "true"}';
One group can be part of many branches

2021-05-10 07:18 UTC, pixie79 commented on flyway/schemas/reference/V137__groups.sql
> +COMMENT ON COLUMN groups.locationid IS '{"label": "Location", "description": "Location of the group.", "summaryview": "true"}';
One group can be part of many locations

2021-05-10 07:20 UTC, pixie79 commented on flyway/schemas/reference/V137__groups.sql
> +COMMENT ON COLUMN groups.name IS '{"label": "Name", "description": "The name of the group.", "businesskey": true, "summaryview": "true"}';
Should this not be group code - there is no point in name / code and display name. Code and display name is better

2021-05-10 07:20 UTC, pixie79 commented on flyway/schemas/reference/V137__groups.sql
> +  displayname VARCHAR(60) NOT NULL,
How long is too long for the screen to make sense - 60 for a group names seems a bit big. Does the UI handle wrapping?

2021-05-10 10:45 UTC, aminmc commented on flyway/schemas/reference/V137__groups.sql
> +COMMENT ON COLUMN groups.teamid IS '{"label": "Team ID", "description": "UUID of the Team which the Group relates to if applicable.", "summaryview": "true"}';
why is this called teamid? Which is it...is it a group or is it a team?

2021-05-10 15:01 UTC, rfndn commented on flyway/schemas/reference/V137__groups.sql
> +  displayname VARCHAR(60) NOT NULL,
It's up to each individual app consuming this data app to handle the wrapping, this repo shouldn't have anything to do with the way the data is displayed.

2021-05-11 10:22 UTC, rfndn commented on flyway/schemas/reference/V137__groups.sql
> +COMMENT ON COLUMN groups.teamid IS '{"label": "Team ID", "description": "UUID of the Team which the Group relates to if applicable.", "summaryview": "true"}';
That's not a business requirement.

2021-05-11 10:23 UTC, rfndn commented on flyway/schemas/reference/V137__groups.sql
> +COMMENT ON COLUMN groups.name IS '{"label": "Name", "description": "The name of the group.", "businesskey": true, "summaryview": "true"}';
There was a clear business requirement for a separate code, group name and group display name.

2021-05-12 14:20 UTC, closed without merging

2021-05-12 14:51 UTC, dolomitejunkie commented
looks good to me with the latest changes

2021-05-13 14:13 UTC, dolomitejunkie commented
all looks good ot me, many thanks